### ISSUE TITLE
有似乎不影响使用的报错

### ISSUE THREAD

**Issue by Jadlokin-Scarlet** [qaralotte/ncmdump#2]
E:\down\CloudMusic\VipSongsDownload>java -jar ncmdump.jar "宮本浩次 - 冬の花.ncm"
correct magic
read key data successfully
aes ecb decrypt successfully
rc4 ksa build sbox successfully
read meta data successfully
meta data:
  music:{"musicId":1345485069,"musicName":"冬の花","artist":[["宮本浩次",159878]],"albumId":75518080,"album":"冬の花","albumPicDocId":"109951163919087485","albumPic":"https://p3.music.126.net/IARWNTyCr1s8tkbgd3V8QA==/109951163919087485.jpg","bitrate":320000,"mp3DocId":"39932e78caf2f045f45c7ebf71ca1fc1","duration":240640,"mvId":14231808,"alias":["日剧《后妻业》主题曲 ； ドラマ『後妻業』主題歌"],"transNames":["冬之花"],"format":"mp3"}
read crc32 successfully
  crc32: -1126060459
read album image successfully
write music file successfully
Exception in thread "main" java.lang.ClassCastException: org.jaudiotagger.tag.id3.ID3v23Tag cannot be cast to org.jaudiotagger.tag.id3.ID3v22Tag
        at io.qaralotte.ncmdump.Dump.execute(Dump.java:56)
        at io.qaralotte.ncmdump.Executor.main(Executor.java:16)

**Comment by qaralotte** [comment]
感谢反馈，已经修复力
