### ISSUE TITLE
ID3 tag cannot be written in File

### ISSUE THREAD

**Issue by hluica** [qaralotte/ncmdump#3]
其他信息均显示正确，比如：
```
Verify .ncm MAGIC => Correct
Read KEY data => Success
AES-ECB decrypt => Success
RC4-KSA build Key Box => Success
Read META data => Success
Read CRC32 => Success
Read album image => Success
Read MUSIC data => Success
Write MUSIC file => Success
```
错误信息为：
```
Fix ID3 Tag => Error
=> ID3 tag cannot be written in File
```
系统版本：Windows 11 insider preview build 23506；
java版本：1.8.0_371-b11；
网易云音乐版本：3.0.0 beta build 201700 和 2.10.11 build 201538 均经过尝试

如果可以的话，希望增加将id3 tag和cover图片导出为单独文件的功能，以在出现以上错误时可手动获取元数据导入。

**Comment by Air003** [comment]
@hluica 
在NcmDump的249行下
AudioFile audioFile = audioFileReader.read(musicFile);

添加
audioFile.createDefaultTag();

可以解决错误
Fix ID3 Tag => Error
=> ID3 tag cannot be written in File
